test_thread_pool: test_thread_pool.cpp XThread.h XThread.cpp XThreadPool.h XThreadPool.cpp XFtpServerCMD.h XFtpServerCMD.cpp
	g++ $^ -o $@ -std=c++11 -levent

clean:
	rm -rf test_thread_pool
	rm -rf *.o
